/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tomek_voicecalculator_calculator_CalculatorLib */

#ifndef _Included_com_tomek_voicecalculator_calculator_CalculatorLib
#define _Included_com_tomek_voicecalculator_calculator_CalculatorLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tomek_voicecalculator_calculator_CalculatorLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tomek_voicecalculator_calculator_CalculatorLib_fibNR
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
